apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-container
        image: adir1306/daily-fact-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
        # --- תוספת קריטית ל-Auto Scaling ---
        resources:
          requests:
            cpu: "100m"  # התחלה: עשירית מעבד
          limits:
            cpu: "500m"  # מקסימום: חצי מעבד
        # -----------------------------------

        envFrom:
        - configMapRef:
            name: app-config
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
