apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-deployment
spec:
  replicas: 5  # <--- שינוי כוח אש: עולים ל-5 עותקים!
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-container
        image: adir1306/daily-fact-app:latest  # <--- המקור החדש בענן
        imagePullPolicy: Always  # <--- תמיד תבדוק אם יש גרסה חדשה בענן
        ports:
        - containerPort: 5000
