apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  type: LoadBalancer # חושף את השירות החוצה למחשב שלך
  selector:
    app: quote-app
  ports:
    - port: 8080        # הפורט שבו נפנה לשירות מבחוץ (בחרתי 8080 כדי שיהיה לך נוח)
      targetPort: 5000  # הפורט שהקונטיינר מאזין לו בפנים
